# https://github.com/golangci/golangci/wiki/Configuration

# Paths here are very specific: the build process will copy the source into `/go/src/{project-path}`
# All commands are run from that directory
service:
  project-path: graphelier/
  analyzed-paths:
    - core/graphelier-service/...
  prepare:
    - go get -t graphelier/core/graphelier-service/...
