version: "3.4"
services:
  graphelier-app:
    build:
      context: ./app
      target: prod
    ports:
      - "3000:3000"
    depends_on:
      - "graphelier-service"
  graphelier-service:
    build:
      context: ./core
      target: prod
    ports:
      - "5050:5050"
    volumes:
      - ./core/graphelier-service:/go/src/graphelier/core/graphelier-service
    depends_on:
      - "mongo"
  mongo:
    build:
      context: ./core/db
    container_name: "graphelier-db"
    ports:
      - "27017:27017"
    volumes:
      - "graphelier-db:/data/db"

volumes:
  graphelier-db:
