version: "3.4"
services:
  graphelier-app:
    build:
      context: ./app
    depends_on:
      - "graphelier-service"
  graphelier-service:
    build:
      context: ./core
    ports:
      - "5050:5050"
    depends_on:
      - "mongo"
  mongo:
    build:
      context: ./core/db
    container_name: "graphelier-db"
    ports:
      - "27017:27017"
    volumes:
      - "graphelier-db:/data/db"

volumes:
  graphelier-db:
