version: "3.4"
services:
  graphelier-app:
    build:
      context: ./app
    depends_on:
      - "graphelier-service"
  graphelier-service:
    build:
      context: ./core
    ports:
      - "5050:5050"
    depends_on:
      - "service-db"
  service-db:
    build:
      context: ./core/db
    container_name: "graphelier-db"
    ports:
      - "27017:27017"
    volumes:
      - "graphelier-db:/data/db"
  graphelier-news:
    build:
      context: ./news/service
    ports:
      - "8080:8080"
    depends_on:
      - "news-db"
    restart: on-failure
  news-db:
    build:
      context: ./news/db
    container_name: "news-db"
    ports:
      - "27016:27017"
    volumes:
      - "news-db:/data/db"

volumes:
  graphelier-db:
  news-db:
