version: 2.1
jobs:
    prepare:
        docker:
            - image: circleci/python:3.7-buster
        working_directory: ~/graphelier
        steps:
            - checkout
            - run: rm -rf .git/
            - persist_to_workspace:
                  root: ~/graphelier
                  paths:
                      - .

    build_app:
        docker:
            - image: circleci/node:10.16.3-buster
        working_directory: ~/graphelier/app
        steps:
            - attach_workspace:
                  at: ~/graphelier
            - restore_cache:
                  keys:
                      - v0-app-{{ checksum "package-lock.json" }}
                      - v0-app-
            - run:
                  name: Install frontend dependencies
                  command: npm install --quiet
            - save_cache:
                  key: v0-app-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/graphelier/app/node_modules
            - run:
                  name: Build frontend app
                  command: npm run build
            - run:
                  name: Test frontend
                  command: npm test
            - run:
                  name: Lint frontend
                  command: npm run lint src/

    build_service:
        docker:
            - image: circleci/golang:1.13-buster
        working_directory: /go/src/graphelier
        steps:
            - restore_cache:
                  keys:
                      - v0-service-{{ .Branch }}
                      - v0-service-master
            - attach_workspace:
                  at: /go/src/graphelier
            - run:
                  name: Build service executable
                  command: go get -t graphelier/core/graphelier-service/...
            - save_cache:
                  key: v2-service-{{ .Branch }}
                  paths:
                      - /go/src/github.com
                      - /go/src/go.mongodb.org
                      - /go/pkg
                      - ~/.cache/go-build
            - run:
                  name: Test service
                  command: go test graphelier/core/graphelier-service/...

    build_scripts:
        docker:
            - image: circleci/python:3.7-buster
        working_directory: ~/graphelier/core/scripts
        steps:
            - attach_workspace:
                  at: ~/graphelier
            - restore_cache:
                  keys:
                      - v0-scripts-{{ checksum "requirements.txt" }}
                      - v0-scripts-
            - run:
                  name: Install scripts dependencies
                  command: |
                      python -m venv venv
                      source venv/bin/activate
                      pip install -r requirements.txt
            - save_cache:
                  key: v0-scripts-{{ checksum "requirements.txt" }}
                  paths:
                      - venv
            - run:
                  name: Test scripts
                  command: |
                      source venv/bin/activate
                      python -m unittest
            - run:
                  name: Lint scripts
                  command: |
                      source venv/bin/activate
                      pylint scripts
orbs:
    aws-ecr: circleci/aws-ecr@6.7.0
    aws-ecs: circleci/aws-ecs@1.0.4
workflows:
    version: 2
    build_and_test:
        jobs:
            - prepare
            - build_app:
                  requires:
                      - prepare
            - build_service:
                  requires:
                      - prepare
            - build_scripts:
                  requires:
                      - prepare
    push_and_deploy:
        jobs:
            - aws-ecr/build-and-push-image:
                  name: build_service_ecr
                  filters:
                      branches:
                          only:
                              - master
                  account-url: AWS_ECR_URL
                  repo: "graphelier-service"
                  region: AWS_DEFAULT_REGION
                  tag: "${CIRCLE_SHA1}"
                  extra-build-args: "--target prod"
                  path: ./core
            - aws-ecr/build-and-push-image:
                  name: build_app_ecr
                  filters:
                      branches:
                          only:
                              - master
                  account-url: AWS_ECR_URL
                  repo: "graphelier-app"
                  region: AWS_DEFAULT_REGION
                  tag: "${CIRCLE_SHA1}"
                  extra-build-args: "--target prod"
                  path: ./app
            - aws-ecr/build-and-push-image:
                  name: build_mongo_ecr
                  filters:
                      branches:
                          only:
                              - master
                  account-url: AWS_ECR_URL
                  repo: "mongo"
                  region: AWS_DEFAULT_REGION
                  tag: "${CIRCLE_SHA1}"
                  path: ./core/db
            - aws-ecs/deploy-service-update:
                  requires:
                      - build_service_ecr
                      - build_app_ecr
                      - build_mongo_ecr
                  filters:
                      branches:
                          only:
                              - master
                  aws-region: AWS_DEFAULT_REGION
                  family: "app"
                  cluster-name: "Graphelier-cluster"
                  service-name: "Graphelier-service"
                  container-image-name-updates: "container=graphelier-app,image-and-tag=graphelier-app:${CIRCLE_SHA1},container=graphelier-service,image-and-tag=graphelier-service:${CIRCLE_SHA1},container=mongo,image-and-tag=mongo:${CIRCLE_SHA1}"
