version: 2
jobs:
    prepare:
        docker:
            - image: circleci/python:3.7-buster
        working_directory: ~/graphelier
        steps:
            - checkout
            - persist_to_workspace:
                  root: ~/graphelier
                  paths:
                      - .

    build_app:
        docker:
            - image: circleci/node:10.16.3-buster
        working_directory: ~/graphelier/app
        steps:
            - attach_workspace:
                  at: ~/graphelier
            - restore_cache:
                  keys:
                      - v1-app-{{ checksum "package-lock.json" }}
                      - v1-app-
            - run:
                  name: Install frontend dependencies
                  command: npm install --quiet
            - save_cache:
                  key: v1-app-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/graphelier/app/node_modules
            - run:
                  name: Build frontend app
                  command: npm run build
            - run:
                  name: Test frontend
                  command: npm test
            - run:
                  name: Lint frontend
                  command: npm run lint src/

    build_service:
        docker:
            - image: circleci/golang:1.13-buster
        working_directory: ~/graphelier/core
        steps:
            - attach_workspace:
                  at: ~/graphelier
            - restore_cache:
                  keys:
                      - v1-service-{{ .Branch }}
                      - v1-service-master
                      - v1-service-
            - run:
                  name: Setup directory structure
                  command: |
                      ln -sfn ~/graphelier /go/src/graphelier
            - run:
                  name: Build service executable
                  command: go get graphelier/core/graphelier-service
            - save_cache:
                  key: v1-service-{{ .Branch }}
                  paths:
                      - /go/src
                      - /go/pkg
                      - ~/.cache/go-build
            - run:
                  name: Test service
                  command: go test graphelier/core/graphelier-service/...

    build_scripts:
        docker:
            - image: circleci/python:3.7-buster
        working_directory: ~/graphelier/core/scripts
        steps:
            - attach_workspace:
                  at: ~/graphelier
            - restore_cache:
                  keys:
                      - v1-scripts-{{ checksum "requirements.txt" }}
                      - v1-scripts-
            - run:
                  name: Install scripts dependencies
                  command: |
                      python -m venv venv
                      source venv/bin/activate
                      pip install -r requirements.txt
            - save_cache:
                  key: v1-scripts-{{ checksum "requirements.txt" }}
                  paths:
                      - venv
            - run:
                  name: Test scripts
                  command: |
                      source venv/bin/activate
                      python -m unittest
            - run:
                  name: Lint scripts
                  command: |
                      source venv/bin/activate
                      pylint scripts

workflows:
    version: 2
    build_and_test:
        jobs:
            - prepare
            - build_app:
                  requires:
                      - prepare
            - build_service:
                  requires:
                      - prepare
            - build_scripts:
                  requires:
                      - prepare
